# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Addison Kline

MESSAGE_SUBJECT_LEN_MIN = 1
MESSAGE_SUBJECT_LEN_MAX = 255

MESSAGE_BODY_LEN_MIN = 1
MESSAGE_BODY_LEN_MAX = 65535

AGENT_NAME_LEN_MIN = 1
AGENT_NAME_LEN_MAX = 31

SWARM_NAME_LEN_MIN = 1
SWARM_NAME_LEN_MAX = 31

DAEMON_WORKER_NAME_LEN_MIN = 1
DAEMON_WORKER_NAME_LEN_MAX = 31

SWARM_DESCRIPTION_LEN_MIN = 0
SWARM_DESCRIPTION_LEN_MAX = 255

SWARM_KEYWORD_LEN_MIN = 1
SWARM_KEYWORD_LEN_MAX = 31
