[project]
name = "acp"
version = "1.0.0"
description = "Agent Communication Protocol"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dict2xml>=1.7.7",
    "langchain-core>=0.3.72",
    "pydantic>=2.11.7",
]
